# Generated by Django 5.0.7 on 2024-07-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(default=None, max_length=255)),
                ('geolocation', models.CharField(default=None, max_length=50)),
                ('menu', models.JSONField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='search.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('offers', models.JSONField(default=None)),
                ('cuisines', models.JSONField(default=None)),
                ('currency', models.CharField(default=None, max_length=255)),
                ('location', models.JSONField(default=None)),
                ('price_range', models.IntegerField(default=None)),
                ('user_rating', models.JSONField(default=None)),
                ('mezzo_provider', models.CharField(default=None, max_length=255, null=True)),
                ('order_deeplink', models.CharField(default=None, max_length=255, null=True)),
                ('has_table_booking', models.IntegerField(default=None)),
                ('is_delivering_now', models.IntegerField(default=None)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='search.restaurant')),
            ],
        ),
    ]
