# Generated by Django 5.0.7 on 2024-07-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantdata',
            old_name='full_details',
            new_name='fullDetails',
        ),
    ]
