# Generated by Django 5.0.7 on 2024-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_full_details_restaurantdata_fulldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
