# Generated by Django 5.0.7 on 2024-07-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_restaurantdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdata',
            name='fullDetails',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='geolocation',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='items',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurantdata',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
